# Generated by Django 5.2.4 on 2025-07-30 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='date',
            field=models.DateField(),
        ),
    ]
