# Generated by Django 5.2.4 on 2025-08-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0003_rename_sessions_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveBigIntegerField(help_text='Duration in minutes'),
        ),
    ]
