# Generated by Django 5.2.4 on 2025-08-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0004_alter_session_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='notes',
        ),
    ]
